/* -----------------------------------------------------------
Query 1: Total Revenue
Purpose:
Calculate the total revenue generated from all sales.
Revenue is calculated as quantity * price.
----------------------------------------------------------- */

SELECT SUM(quantity * price) AS total_revenue
FROM retail_sales;



/* -----------------------------------------------------------
Query 2: Revenue by Product
Purpose:
Identify which products generate the most revenue.
Useful for product performance analysis.
----------------------------------------------------------- */

SELECT product,
       SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY product
ORDER BY revenue DESC;



/* -----------------------------------------------------------
Query 3: Revenue by Category
Purpose:
Analyze which product categories generate the highest revenue.
----------------------------------------------------------- */

SELECT category,
       SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY category
ORDER BY revenue DESC;



/* -----------------------------------------------------------
Query 4: Revenue by City
Purpose:
Identify which cities generate the most sales revenue.
Helps understand geographic sales performance.
----------------------------------------------------------- */

SELECT city,
       SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY city
ORDER BY revenue DESC;



/* -----------------------------------------------------------
Query 5: Total Orders per Customer
Purpose:
Determine how many orders each customer has placed.
Helps identify active customers.
----------------------------------------------------------- */

SELECT customer_id,
       COUNT(order_id) AS total_orders
FROM retail_sales
GROUP BY customer_id
ORDER BY total_orders DESC;



/* -----------------------------------------------------------
Query 6: Top 3 Customers by Revenue
Purpose:
Identify the most valuable customers based on spending.
----------------------------------------------------------- */

SELECT customer_id,
       SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY customer_id
ORDER BY revenue DESC
LIMIT 3;



/* -----------------------------------------------------------
Query 7: Average Order Value
Purpose:
Calculate the average revenue generated per order.
----------------------------------------------------------- */

SELECT AVG(quantity * price) AS avg_order_value
FROM retail_sales;



/* -----------------------------------------------------------
Query 8: Repeat Customers
Purpose:
Identify customers who placed more than one order.
These customers are important for customer retention analysis.
----------------------------------------------------------- */

SELECT customer_id
FROM retail_sales
GROUP BY customer_id
HAVING COUNT(order_id) > 1;



/* -----------------------------------------------------------
Query 9: Monthly Revenue Trend
Purpose:
Analyze how revenue changes over time (month-wise).
Useful for identifying seasonality and sales trends.
----------------------------------------------------------- */

SELECT DATE_TRUNC('month', order_date) AS month,
       SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY month
ORDER BY month;



/* -----------------------------------------------------------
Query 10: Ranking Customers by Revenue
Purpose:
Rank customers based on their total spending.
Uses window function RANK().
----------------------------------------------------------- */

SELECT customer_id,
       SUM(quantity * price) AS revenue,
       RANK() OVER (ORDER BY SUM(quantity * price) DESC) AS revenue_rank
FROM retail_sales
GROUP BY customer_id;



/* -----------------------------------------------------------
Query 11: Top Selling Products by Quantity
Purpose:
Identify which products sell the most units.
----------------------------------------------------------- */

SELECT product,
       SUM(quantity) AS total_units_sold
FROM retail_sales
GROUP BY product
ORDER BY total_units_sold DESC;



/* -----------------------------------------------------------
Query 12: Revenue Contribution by Category
Purpose:
Understand how much each category contributes to total sales.
----------------------------------------------------------- */

SELECT category,
       SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY category
ORDER BY revenue DESC;



/* -----------------------------------------------------------
Query 13: Customer Lifetime Value (CLV)
Purpose:
Calculate total revenue generated by each customer.
Helps identify high-value customers.
----------------------------------------------------------- */

SELECT customer_id,
       SUM(quantity * price) AS customer_lifetime_value
FROM retail_sales
GROUP BY customer_id
ORDER BY customer_lifetime_value DESC;



/* -----------------------------------------------------------
Query 14: Revenue Share by Product
Purpose:
Calculate how much each product contributes to total revenue.
----------------------------------------------------------- */

SELECT product,
       SUM(quantity * price) AS revenue,
       SUM(quantity * price) * 100.0 /
       SUM(SUM(quantity * price)) OVER () AS revenue_percentage
FROM retail_sales
GROUP BY product
ORDER BY revenue DESC;



/* -----------------------------------------------------------
Query 15: Running Total Revenue
Purpose:
Track cumulative revenue over time.
Useful for monitoring sales growth.
----------------------------------------------------------- */

SELECT order_date,
       SUM(quantity * price) AS daily_revenue,
       SUM(SUM(quantity * price)) OVER (ORDER BY order_date) AS running_revenue
FROM retail_sales
GROUP BY order_date
ORDER BY order_date;



/* -----------------------------------------------------------
Query 16: Rank Products by Revenue
Purpose:
Rank products based on total revenue using RANK().
----------------------------------------------------------- */

SELECT product,
       SUM(quantity * price) AS revenue,
       RANK() OVER (ORDER BY SUM(quantity * price) DESC) AS product_rank
FROM retail_sales
GROUP BY product;



/* -----------------------------------------------------------
Query 17: Customer Order Ranking
Purpose:
Rank customers based on the number of orders placed.
----------------------------------------------------------- */

SELECT customer_id,
       COUNT(order_id) AS total_orders,
       RANK() OVER (ORDER BY COUNT(order_id) DESC) AS order_rank
FROM retail_sales
GROUP BY customer_id;



/* -----------------------------------------------------------
Query 18: Daily Revenue Change
Purpose:
Calculate revenue difference between consecutive days.
Uses LAG() window function.
----------------------------------------------------------- */

SELECT order_date,
       SUM(quantity * price) AS revenue,
       LAG(SUM(quantity * price))
       OVER (ORDER BY order_date) AS previous_day_revenue
FROM retail_sales
GROUP BY order_date
ORDER BY order_date;



/* -----------------------------------------------------------
Query 19: Highest Revenue Order
Purpose:
Identify the order that generated the highest revenue.
----------------------------------------------------------- */

SELECT order_id,
       product,
       quantity * price AS order_revenue
FROM retail_sales
ORDER BY order_revenue DESC
LIMIT 1;



/* -----------------------------------------------------------
Query 20: Top Product per Category
Purpose:
Find the highest revenue product in each category.
Uses window function with PARTITION BY.
----------------------------------------------------------- */

SELECT category,
       product,
       SUM(quantity * price) AS revenue,
       RANK() OVER (
           PARTITION BY category
           ORDER BY SUM(quantity * price) DESC
       ) AS category_rank
FROM retail_sales
GROUP BY category, product;



/* -----------------------------------------------------------
Query 21: Average Revenue per Customer
Purpose:
Calculate average revenue generated per customer.
----------------------------------------------------------- */

SELECT customer_id,
       AVG(quantity * price) AS avg_customer_revenue
FROM retail_sales
GROUP BY customer_id
ORDER BY avg_customer_revenue DESC;



/* -----------------------------------------------------------
Query 22: Top City by Revenue
Purpose:
Identify which city contributes the highest sales revenue.
----------------------------------------------------------- */

SELECT city,
       SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY city
ORDER BY revenue DESC
LIMIT 1;



/* -----------------------------------------------------------
Query 23: Customer Orders with Names
Purpose:
Join sales with customers table to display customer names
instead of only customer IDs.
----------------------------------------------------------- */

SELECT
    c.customer_name,
    r.order_id,
    r.product,
    r.quantity,
    r.price
FROM retail_sales r
JOIN customers c
ON r.customer_id = c.customer_id;



/* -----------------------------------------------------------
Query 24: Revenue by Customer Name
Purpose:
Calculate total revenue generated by each customer.
----------------------------------------------------------- */

SELECT
    c.customer_name,
    SUM(r.quantity * r.price) AS total_revenue
FROM retail_sales r
JOIN customers c
ON r.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY total_revenue DESC;



/* -----------------------------------------------------------
Query 25: Revenue by Product Category
Purpose:
Join sales with products table to analyze category performance.
----------------------------------------------------------- */

SELECT
    p.category,
    SUM(r.quantity * r.price) AS revenue
FROM retail_sales r
JOIN products p
ON r.product_id = p.product_id
GROUP BY p.category
ORDER BY revenue DESC;



/* -----------------------------------------------------------
Query 26: Top Customers by Revenue
Purpose:
Identify high-value customers.
----------------------------------------------------------- */

SELECT
    c.customer_name,
    SUM(r.quantity * r.price) AS revenue
FROM retail_sales r
JOIN customers c
ON r.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY revenue DESC
LIMIT 5;



/* -----------------------------------------------------------
Query 27: Rank Customers by Revenue
Purpose:
Use window function to rank customers by total spending.
----------------------------------------------------------- */

SELECT
    c.customer_name,
    SUM(r.quantity * r.price) AS revenue,
    RANK() OVER (
        ORDER BY SUM(r.quantity * r.price) DESC
    ) AS customer_rank
FROM retail_sales r
JOIN customers c
ON r.customer_id = c.customer_id
GROUP BY c.customer_name;



/* -----------------------------------------------------------
Query 28: Running Revenue Over Time
Purpose:
Track cumulative revenue growth over time.
----------------------------------------------------------- */

SELECT
    order_date,
    SUM(quantity * price) AS daily_revenue,
    SUM(SUM(quantity * price))
    OVER (ORDER BY order_date) AS running_total_revenue
FROM retail_sales
GROUP BY order_date
ORDER BY order_date;



/* -----------------------------------------------------------
Query 29: Customer Lifetime Value
Purpose:
Measure total spending by each customer.
----------------------------------------------------------- */

SELECT
    customer_id,
    SUM(quantity * price) AS customer_lifetime_value
FROM retail_sales
GROUP BY customer_id
ORDER BY customer_lifetime_value DESC;



/* -----------------------------------------------------------
Query 30: Product Sales Ranking
Purpose:
Rank products by revenue.
----------------------------------------------------------- */

SELECT
    p.product_name,
    SUM(r.quantity * r.price) AS revenue,
    RANK() OVER (
        ORDER BY SUM(r.quantity * r.price) DESC
    ) AS product_rank
FROM retail_sales r
JOIN products p
ON r.product_id = p.product_id
GROUP BY p.product_name;



/* -----------------------------------------------------------
Query 31: City Level Sales Analysis
Purpose:
Identify cities contributing the most revenue.
----------------------------------------------------------- */

SELECT
    city,
    SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY city
ORDER BY revenue DESC;



/* -----------------------------------------------------------
Query 32: Average Revenue per Customer
Purpose:
Measure spending behavior of customers.
----------------------------------------------------------- */

SELECT
    customer_id,
    AVG(quantity * price) AS avg_order_value
FROM retail_sales
GROUP BY customer_id;



/* -----------------------------------------------------------
Query 33: Revenue Above Average Price
Purpose:
Find orders where price is higher than the average price.
Demonstrates use of subqueries.
----------------------------------------------------------- */

SELECT *
FROM retail_sales
WHERE price >
(
    SELECT AVG(price)
    FROM retail_sales
);



/* -----------------------------------------------------------
Query 34: Customer Revenue Using CTE
Purpose:
Use a Common Table Expression to calculate customer revenue
and filter high-value customers.
----------------------------------------------------------- */

WITH customer_revenue AS (
    SELECT
        customer_id,
        SUM(quantity * price) AS revenue
    FROM retail_sales
    GROUP BY customer_id
)

SELECT *
FROM customer_revenue
WHERE revenue > 20000
ORDER BY revenue DESC;



/* -----------------------------------------------------------
Query 35: Latest Order per Customer
Purpose:
Use ROW_NUMBER to find the most recent order per customer.
----------------------------------------------------------- */

SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER(
               PARTITION BY customer_id
               ORDER BY order_date DESC
           ) AS rn
    FROM retail_sales
) t
WHERE rn = 1;



/* -----------------------------------------------------------
Query 36: Revenue Percentage Contribution by Product
Purpose:
Calculate what percentage of total revenue each product contributes.
----------------------------------------------------------- */

SELECT
    product,
    SUM(quantity * price) AS revenue,
    SUM(quantity * price) * 100.0 /
    SUM(SUM(quantity * price)) OVER () AS revenue_percentage
FROM retail_sales
GROUP BY product
ORDER BY revenue DESC;



/* -----------------------------------------------------------
Query 37: Monthly Sales Analysis
Purpose:
Analyze revenue trends by month.
----------------------------------------------------------- */

SELECT
    DATE_TRUNC('month', order_date) AS month,
    SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY month
ORDER BY month;



/* -----------------------------------------------------------
Query 38: Month-over-Month Revenue Change
Purpose:
Compare revenue between consecutive months using LAG.
----------------------------------------------------------- */

SELECT
    month,
    revenue,
    revenue - LAG(revenue) OVER(ORDER BY month) AS revenue_change
FROM (
    SELECT
        DATE_TRUNC('month', order_date) AS month,
        SUM(quantity * price) AS revenue
    FROM retail_sales
    GROUP BY month
) t
ORDER BY month;



/* -----------------------------------------------------------
Query 39: Top Product per Category
Purpose:
Find highest revenue product within each category.
Uses PARTITION BY window function.
----------------------------------------------------------- */

SELECT *
FROM (
    SELECT
        p.category,
        p.product_name,
        SUM(r.quantity * r.price) AS revenue,
        RANK() OVER(
            PARTITION BY p.category
            ORDER BY SUM(r.quantity * r.price) DESC
        ) AS category_rank
    FROM retail_sales r
    JOIN products p
    ON r.product_id = p.product_id
    GROUP BY p.category, p.product_name
) ranked
WHERE category_rank = 1;



/* -----------------------------------------------------------
Query 40: Customer Purchase Frequency
Purpose:
Measure how frequently customers place orders.
----------------------------------------------------------- */

SELECT
    customer_id,
    COUNT(order_id) AS purchase_frequency
FROM retail_sales
GROUP BY customer_id
ORDER BY purchase_frequency DESC;



/* -----------------------------------------------------------
Query 41: Highest Revenue Day
Purpose:
Identify the day with the highest revenue.
----------------------------------------------------------- */

SELECT
    order_date,
    SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY order_date
ORDER BY revenue DESC
LIMIT 1;



/* -----------------------------------------------------------
Query 42: Top 5 Cities by Revenue
Purpose:
Analyze geographic sales performance.
----------------------------------------------------------- */

SELECT
    city,
    SUM(quantity * price) AS revenue
FROM retail_sales
GROUP BY city
ORDER BY revenue DESC
LIMIT 5;



/* ===========================================================
SECTION: JOIN-Based Business Analysis Queries
Purpose:
Use table relationships to analyze customer behavior,
product performance, and sales insights.
=========================================================== */


/* -----------------------------------------------------------
Query 43: Join Sales with Customers
Purpose:
Attach customer names to each order.
----------------------------------------------------------- */

SELECT
    r.order_id,
    c.customer_name,
    r.product,
    r.quantity,
    r.price
FROM retail_sales r
JOIN customers c
ON r.customer_id = c.customer_id;



/* -----------------------------------------------------------
Query 44: Join Sales with Products
Purpose:
Attach product category information to each sale.
----------------------------------------------------------- */

SELECT
    r.order_id,
    p.product_name,
    p.category,
    r.quantity,
    r.price
FROM retail_sales r
JOIN products p
ON r.product_id = p.product_id;



/* -----------------------------------------------------------
Query 45: Join All Tables
Purpose:
Create a complete view of each transaction including
customer and product details.
----------------------------------------------------------- */

SELECT
    r.order_id,
    r.order_date,
    c.customer_name,
    p.product_name,
    p.category,
    r.quantity,
    r.price
FROM retail_sales r
JOIN customers c
ON r.customer_id = c.customer_id
JOIN products p
ON r.product_id = p.product_id;



/* -----------------------------------------------------------
Query 46: Customer Lifetime Value
Purpose:
Calculate total revenue generated by each customer.
----------------------------------------------------------- */

SELECT
    c.customer_name,
    SUM(r.quantity * r.price) AS total_spent
FROM retail_sales r
JOIN customers c
ON r.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY total_spent DESC;



/* -----------------------------------------------------------
Query 47: Revenue by Product Category
Purpose:
Identify which product categories generate the most revenue.
----------------------------------------------------------- */

SELECT
    p.category,
    SUM(r.quantity * r.price) AS total_revenue
FROM retail_sales r
JOIN products p
ON r.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;



/* -----------------------------------------------------------
Query 48: Orders per Customer
Purpose:
Measure customer purchase frequency.
----------------------------------------------------------- */

SELECT
    c.customer_name,
    COUNT(r.order_id) AS total_orders
FROM retail_sales r
JOIN customers c
ON r.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY total_orders DESC;



/* -----------------------------------------------------------
Query 49: Customers Without Orders
Purpose:
Find customers who signed up but never placed an order.
----------------------------------------------------------- */

SELECT
    c.customer_name
FROM customers c
LEFT JOIN retail_sales r
ON c.customer_id = r.customer_id
WHERE r.order_id IS NULL;



/* -----------------------------------------------------------
Query 50: Top Product by Revenue
Purpose:
Identify the highest revenue generating product.
----------------------------------------------------------- */

SELECT
    p.product_name,
    SUM(r.quantity * r.price) AS revenue
FROM retail_sales r
JOIN products p
ON r.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 1;



/* ===========================================================
SECTION: Advanced Window Function Queries
Purpose:
Use window functions to rank products, analyze trends,
and calculate cumulative revenue.
=========================================================== */


/* -----------------------------------------------------------
Query 51: Rank Products by Revenue
Purpose:
Rank products based on total revenue generated.
----------------------------------------------------------- */

SELECT
    product,
    SUM(quantity * price) AS total_revenue,
    RANK() OVER (ORDER BY SUM(quantity * price) DESC) AS revenue_rank
FROM retail_sales
GROUP BY product;



/* -----------------------------------------------------------
Query 52: Top Revenue Order per Customer
Purpose:
Identify the highest-value purchase made by each customer.
----------------------------------------------------------- */

SELECT
    customer_id,
    order_id,
    quantity * price AS order_value,
    ROW_NUMBER() OVER (
        PARTITION BY customer_id
        ORDER BY quantity * price DESC
    ) AS order_rank
FROM retail_sales;



/* -----------------------------------------------------------
Query 53: Running Total Revenue Over Time
Purpose:
Calculate cumulative revenue across dates.
----------------------------------------------------------- */

SELECT
    order_date,
    SUM(quantity * price) AS daily_revenue,
    SUM(SUM(quantity * price)) OVER (ORDER BY order_date)
        AS cumulative_revenue
FROM retail_sales
GROUP BY order_date
ORDER BY order_date;



/* -----------------------------------------------------------
Query 54: Rank Cities by Revenue
Purpose:
Compare city performance using ranking.
----------------------------------------------------------- */

SELECT
    city,
    SUM(quantity * price) AS revenue,
    RANK() OVER (ORDER BY SUM(quantity * price) DESC) AS city_rank
FROM retail_sales
GROUP BY city;



/* -----------------------------------------------------------
Query 55: Revenue Contribution by Product
Purpose:
Calculate percentage contribution of each product to total revenue.
----------------------------------------------------------- */

SELECT
    product,
    SUM(quantity * price) AS revenue,
    ROUND(
        SUM(quantity * price) * 100.0 /
        SUM(SUM(quantity * price)) OVER (),
        2
    ) AS revenue_percentage
FROM retail_sales
GROUP BY product
ORDER BY revenue DESC;